#!/bin/bash

# IMPORTANT
# ---------
# Originally generated by React CDK, which this project no longer uses — edits
# here are intentional. Project-specific steps still belong in
# `.scripts/user/prepublish.sh`.

# Every step must be able to fail the build. This script is `prepublishOnly`, so
# without `set -e` a failed babel run is swallowed — the exit status comes from
# the last command — and npm publishes a partial or empty dist/.
set -e

echo "=> Transpiling 'src' into ES5 ..."
echo ""
rm -rf ./dist
NODE_ENV=production BABEL_ENV=cjs ./node_modules/.bin/babel --extensions ".ts,.tsx" --ignore "**/__tests__/**","**/stories/**","**/setupTests.js" ./src --out-dir ./dist

echo "=> Transpiling 'src' into ES6 ..."
NODE_ENV=production BABEL_ENV=es ./node_modules/.bin/babel --extensions ".ts,.tsx" --ignore "**/__tests__/**","**/stories/**","**/setupTests.js" ./src --out-dir ./dist/es

echo "=> Transpiling 'src' into UMD ..."
NODE_ENV=production BABEL_ENV=umd ./node_modules/.bin/babel --extensions ".ts,.tsx" --ignore "**/__tests__/**","**/stories/**","**/setupTests.js" ./src --out-dir ./dist/umd

echo "=> Transpiling 'src' into NEXT ..."
NODE_ENV=production BABEL_ENV=next ./node_modules/.bin/babel --extensions ".ts,.tsx" --ignore "**/__tests__/**","**/stories/**","**/setupTests.js" ./src --out-dir ./dist/next

echo ""
echo "=> Transpiling completed."

. .scripts/user/prepublish.sh